version: '3'

services:
  api:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "recommendation.app:create_app()"
    env_file:
      - '.env'
    volumes:
      - '.:/recommendation'
    ports:
      - '8000:8000'
    depends_on:
      - postgres

  postgres:
    image: postgres:12-alpine
    env_file:
      - '.env'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

volumes:
  postgres: